apiVersion: v1
kind: Pod
metadata:
  name: Firstpod
  namespace: krishan
  labels:
    app: home
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80  
    containers:
  - name: nginx2
    image: nginx
    ports:
    - containerPort: 80  
